services:
  my-app:
    build:
      context: .
      args:
        STUDENT_NAME: "Andre Gamalion"
        STUDENT_NIM: "00000076974"
    ports:
      # TODO
      - 80:3000
    environment:
      NODE_ENV: development
    volumes:
      - .:/use/src/app
    command: "npm run dev"
